### ISSUE TITLE
[covid] What to (practically) do if you're actually sick

### ISSUE THREAD

**Issue by simoncozens** [raphlinus/raphlinus.github.io#20]
The Atlantic article doesn't *really* cover this - it's more kvetching about testing protocols and government responses. I did read something about what medicines to give etc. but I can't find it now. :/

This is something: https://www.who.int/publications-detail/home-care-for-patients-with-suspected-novel-coronavirus-(ncov)-infection-presenting-with-mild-symptoms-and-management-of-contacts
Here is the UK version: https://www.gov.uk/government/publications/covid-19-stay-at-home-guidance/stay-at-home-guidance-for-people-with-confirmed-or-possible-coronavirus-covid-19-infection

**Comment by davelab6** [comment]
Seems important and well cited: Using common household painkillers and fever reducing drugs like ibuprofen and acetaminophen and paracetamol will reduce the effectiveness of your immune response (the fever needs to run hot)

https://youtu.be/EuWo5lmWuZI

Re prevention

https://youtu.be/W5yVGmfivAk

**Comment by raphlinus** [comment]
I'll put that in there when it gets cited by at least two major public health organizations, or a doctor on my epidemiology list who is sounding the alarm about potential damage.

**Comment by raphlinus** [comment]
Closing this, as I'm incorporating Simon's good references.

**Comment by davelab6** [comment]
https://www.theguardian.com/world/2020/mar/16/health-experts-criticise-nhs-advice-to-take-ibuprofen-for-covid-19 has more sourcing for the anti ibuprofen thing

**Comment by raphlinus** [comment]
Yup, it's good for a general audience, and I believe is in line with the source I linked.
