### ISSUE TITLE
Flattening quadratic Béziers: Question about constant value

### ISSUE THREAD

**Issue by yurivish** [raphlinus/raphlinus.github.io#57]
Hi Raph,

I have a question about the following code, based on [this section](https://scholarsarchive.byu.edu/cgi/viewcontent.cgi?article=1000&context=facpub#section.10.6) of Sederberg's notes mentioned in your [post](https://raphlinus.github.io/graphics/curves/2019/12/23/flatten-quadbez.html).

```js
// Subdivide using method from Sederberg's CAGD notes
subdiv_sederberg(tol, round_to_pow2) {
    const ddx = 2 * this.x1 - this.x0 - this.x2;
    const ddy = 2 * this.y1 - this.y0 - this.y2;
    const dd = Math.hypot(ddx, ddy);
    let n = Math.ceil(Math.sqrt(0.25 * dd / tol));
    if (round_to_pow2) {
        n = 1 << 32 - Math.clz32(n - 1);
    }
    let result = [];
    for (let i = 0; i < n; i++) {
        const t = i / n;
        result.push(t);
    }
    result.push(1);
    return result;
}
```

The notes give the following formula, where the divisor is 8 * tol:

![image](https://user-images.githubusercontent.com/114388/123496096-7bc24d80-d5f4-11eb-9d7e-49f8107fd6af.png)

However, in the code above, the divisor appears to be effectively 4 * tol:

```js
    let n = Math.ceil(Math.sqrt(0.25 * dd / tol));
```

Is the `0.25` intentional, or is it a typo, and meant to be `0.125`?

**Comment by raphlinus** [comment]
That's a super good question. I don't recall the derivation, and it's possible it's imprecise. The best way to resolve this would be to measure the range of errors and see that the distribution comes right up to the stated tolerance.

**Comment by yurivish** [comment]
Good point. Some quick visual checks in Figma suggest your constant is right (or at least I think I've found some curves where `0.125` produces results that are off by more than the stated margin)! I wonder how to square that with the original exposition... 

I looked at this curve on a 300x300 canvas with a tolerance of 15 and a constant value of `0.125`. Black is the curve, red is the polyline approximation:
```
b = ({
  x0: 0,
  y0: 0,
  x1: 500,
  y1: 150,
  x2: 0,
  y2: 300
})
```

![untitled (36)](https://user-images.githubusercontent.com/114388/123496679-479c5c00-d5f7-11eb-92d1-fd1c724fbce1.png)

Not very rigorous, but that gap is significantly more than 15 pixels across at the widest point.

**Comment by raphlinus** [comment]
Yes, same units. I must say, I haven't done rigorous checking, as I was exploring qualitative features of the algorithm (and you generally tune the tolerance visually anyway). I have hopes of doing an academic paper at some point, which would be a good opportunity to check this stuff more closely.

Also be aware that the tolerance near a cusp can be exceeded with the algorithm in the blog post. There's a refined version (without a proper writeup) that uses different logic when the quadratic segment contains a curvature maximum: https://levien.com/tmp/flatten.html
