### ISSUE TITLE
Advice for the next dozen Rust GUIs

### ISSUE THREAD

**Issue by raphlinus** [raphlinus/raphlinus.github.io#68]
This is a blog post surveying the state of Rust GUI and the position of Druid within that space. It's something of a sequel to [Rust 2020: GUI and community]. Covers similar ground to [Colin's infrastructure post][So you want to write a GUI framework].

Big giant tradeoff space. Small differences in requirements can lead to pretty big differences in design.

Difficult to resolve tradeoffs: how much to use native platform capabilities (incl drawing and esp text) vs build your own. How much to use the compositor. Observation: heavy use of compositor optimizes smooth low-power scrolling but constrains applications in other ways ([compositor is evil]). Also, compositor is not available on Windows 7 and X11. Compatibility is a very tricky issue: wgpu has a particular compatibility matrix; DX11 and OpenGL are planned but are likely to be a compromise. Piet was an attempt to abstract this tradeoff for drawing but was not compelling to community; no other real uses of piet outside Druid.

List some other potential goals (outside Druid scope): integration with 3D, with Webview, with media playback, targeting mobile, scripting support.

Goal of Rust GUI is still compelling. Meanwhile Electron is winning decisively. Web-based platform is seeing a huge investment and has excellent support for accessibility, developer experience, and cross-platform compatibility. Main downside is bloat and lack of crisp responsiveness.

Dear reader is presumed to want to build a GUI application in Rust (I may write this section in 2nd person). They will evaluate the existing tk's, of which Druid, iced, and egui are strong contenders, and come to the conclusion that none quite fit the needs, and in fact want to target a different point in the tradeoff space. Possible to build real product by investing *lots* of effort; could use some existing project as starting point or build anew.

## winit vs druid-shell split

winit is very well suited to game and game-like use cases. A goal of druid-shell is supporting IME well, necessary for a proper text widget. Druid-shell also supports native platform menus and (to some extent) subwindows. That said, winit has a lot of momentum, and d-s has limitations (being too tightly tied to piet). We need to resolve that one way or other. If winit can come up to speed on missing features present in d-s, we'd be happy to move to winit. Coordination is hard. Open to discussion.

## Recap of crochet

Crochet project was emulation of imgui on top of retained. It also tested async and language bindings (Python). Conclusion: it would be possible to build UI on this, but many papercuts. "State tearing" issue. No good compile-time way to ensure sync of begin/end container. No satisfying syntax for properties. Also not great: single-threaded context, which defeats multithreading.

## Review of newer work
* RUI
* Dioxus 

(I haven't actually studied either of these in detail yet, and would like to)

## Accessibility

We support AccessKit. Accessibility is very important and is a requirement for a GUI tk to be "real." Very few do this well.

## Going forward

Development of current Druid branch is slowing down. My personal focus is piet-gpu. It's possible to make a drawing experience (including text) that's much better than current state of the art. One goal for piet-gpu is multithreading. No promises but the goal remains to make piet-gpu real and there has been much progress. Also sensing some interest from community; cite gio work. Happy for others to adapt the ideas.

Likely to explore a research branch (lasagna). How much to go into detail? Raph personal goals are to provide illuminating research for the community rather than to herd cats.

[So you want to write a GUI framework]: https://www.cmyr.net/blog/gui-framework-ingredients.html
[Rust 2020: GUI and community]: https://raphlinus.github.io/rust/druid/2019/10/31/rust-2020.html
[compositor is evil]: https://raphlinus.github.io/ui/graphics/2020/09/13/compositor-is-evil.html

**Comment by derekdreery** [comment]
I tried to understand dioxus but they don't have much prose on their website (it's all marketing essentially). I *think* they have their own custom DOM and use a web view (html) to render, but I might have read wrong. So their stack would resemble an immediate layer -> lasagne -> piet kinda structure. Interesting if this `ergonomic lib -> retained tree -> 2d drawing` stack is independently discovered by different people - possible anecdotal evidence that it's the right approach.

I know flutter uses skia for the piet layer, but how does flutter (and jetpack compose for that matter) handle the API <-> retained tree problem?

**Comment by raphlinus** [comment]
An observation that won't go into the blog post: it's difficult to find good information on what makes UIs tick, as public info tends to be more marketing driven. There are good and bad examples, which I won't list here.

Both Jetpack Compose and Flutter have pretty good explanations of internals. Leonard has some [blog posts](https://medium.com/androiddevelopers/understanding-jetpack-compose-part-1-of-2-ca316fe39050) on the Composer idea. Flutter has a good [talk](https://www.youtube.com/watch?v=UUfXWzp0-DU) on their rendering pipeline, with a good focus on layout.

Here's a radically simplified view of Flutter. Basically, there's a [render object](https://api.flutter.dev/flutter/rendering/RenderObject-class.html) tree which operates pretty similarly to a traditional object-oriented GUI. It is *possible* to write GUI entirely in this and avoid the reactive layer, but nobody actually does. The usual way is to create a Widget tree every app-paint cycle, then that's diffed against the old one using techniques similar to React (vdom), and the result of that diff is updates to the render object tree. Render objects paint into a painting context (which is basically Skia under the hood), but that might well be into an intermediate retained layer rather than direct to the surface (as currently the case in Druid) - you can see a bunch of methods in the RenderObject signature for explicitly managing layers and compositing.

Jetpack Compose is broadly similar, but different in details. It's pretty common for a node managed by Composer to essentially be a lambda that can paint itself to an actual Skia render context. This stuff was fresher in my mind.

My understanding of Dioxus is that it's currently all web tech (so DOM) under the hood, though they envision a future more-native renderer. My suspicion is that if and when that gets built out, it will architecturally be pretty similar to Sciter, which you can think of as a mini HTML/CSS engine purpose-built for supporting UI (and, these days I think, as often programmed directly in React as anything else). I'm interested in *claims* that people have an application API in Rust that's as smooth as React is in JS. The *intent* of lasagna is that it can support lots of different high level architectures (including in the same runtime, ie stitched together), but this is of the more speculative directions.

**Comment by derekdreery** [comment]
I think the big gap at the moment isn't code (there's probably too much of that I think). I think the big gap is a discussion and some documentation around the design space.

 - What aspects are there where there is a 'right' way to do things (maybe immediate API on top of retained scene graph (tree specifically) would fit here)
 -  What aspects are there where the isn't an obviously best way to do things (for example FRP vs tree + diff vs just operating directly on the retained tree).

I feel like we need some shared language to use so we can start comparing different efforts more effectively.

**Comment by derekdreery** [comment]
I think there are some web libs as well that although they target the DOM do provide other ways to actually present the API. [`dominator`](https://crates.io/crates/dominator) uses signals (which IIUC is a FRP method), and [`dodrio`](https://crates.io/crates/dodrio) which tries to push performance on the diff approach using bump arenas.

**Comment by dvc94ch** [comment]
> List some other potential goals (outside Druid scope): targeting mobile

Wondering what makes piet-gpu + xilem + druid-shell (which seems like where druid is heading) fundamentally unsuitable for mobile ui. More reliance on touchscreens vs mouse+keyboard and typically single window (although most desktop applications are single window too) don't seem to fit the bill.

**Comment by raphlinus** [comment]
There's nothing that makes any of this fundamentally unsuitable for mobile, it's almost entirely a question of focus. Mobile does require IME as well as other things, and unfortunately the build/deployment story is a lot more complicated than desktop. It'll be good to clarify this, because a lot of the work on piet-gpu etc actually *does* make sense to target mobile, and it's also an area where people may still care somewhat about performance and resource usage.

**Comment by maroider** [comment]
> winit is very well suited to game and game-like use cases. A goal of druid-shell is supporting IME well, necessary for a proper text widget. Druid-shell also supports native platform menus and (to some extent) subwindows. That said, winit has a lot of momentum, and d-s has limitations (being too tightly tied to piet). We need to resolve that one way or other. If winit can come up to speed on missing features present in d-s, we'd be happy to move to winit. Coordination is hard. Open to discussion.

Are there other features beyond IME support, native menus, and subwindows that you find are missing in winit?

I do admittedly have some good news to share on the IME front, in that we recently merged an improved API into `master`.

**Comment by dvc94ch** [comment]
> unfortunately the build/deployment story is a lot more complicated than desktop

Believe I've been making a lot of progress there with xbuild. There is currently a focus on flutter, but supporting druid once piet-gpu settles is very much a goal of mine.

In my experience the build/deployment story is not a lot more complicated on mobile. code signing, notarization and creating dmg's for Mac from Linux is comparably complicated to signing, uploading and debugging an iOS app. In my experience I'd say each platform is equally complicated with the constraint that you must be able to cross compile from Linux/macos/windows.

**Comment by raphlinus** [comment]
> Are there other features beyond IME support, native menus, and subwindows that you find are missing in winit?

My biggest concern is the quality of keyboard support, which seems to be a real issue (affecting alacritty and lapce, among other things). Reading through https://github.com/rust-windowing/winit/pull/1890 is worrisome. I believe the Windows handling in druid-shell is extremely good, the mac handling is fairly good (a lot depends on the quality of integration with IME, which I haven't rigorously tested yet), and Linux has problems. I'm happy for people to steal ideas and code, and I think 1890 is broadly similar to my approach.

Keyboard is especially complicated because it overlaps so many other areas - accelerators for menus and so on. It is one of the reasons why I believe winit's stated scope of getting a window on the screen, what happens in the window is up to the client, is misguided.

There are other features druid-shell has, like copy-paste (it's quite good, we've successfully roundtripped glyphs with other font editors), but to a large extent I think those can be done as a separate crate on top of winit.

> In my experience the build/deployment story is not a lot more complicated on mobile.

Right, I mean it's more complicated in practice because you have to do cross-compilation. A very important part of the druid experience is that "cargo build" just works, and unfortunately that's not an option on mobile.

**Comment by maroider** [comment]
> My biggest concern is the quality of keyboard support, which seems to be a real issue (affecting alacritty and lapce, among other things).

I believe most of the work required to get us to a *fairly* acceptable state has already been done. We "just" need to rebase, test, and merge it (although there are some known issues that I'd also like to get fixed).

> Keyboard is especially complicated because it overlaps so many other areas - accelerators for menus and so on. It is one of the reasons why I believe winit's stated scope of getting a window on the screen, what happens in the window is up to the client, is misguided.

I'll admit that the tension between what winit's stated scope is, and that which might be most "natural", isn't entirely lost on me. We do need *some* way of delineating that which belongs in winit and that which does not, and it has been easier to stick with the status quo in this regard than to re-consider and/or change it, but it's something I'm open to discussing going forward.
