### ISSUE TITLE
About the Fuschia text renderer

### ISSUE THREAD

**Issue by LifeIsStrange** [raphlinus/raphlinus.github.io#69]
Hi @raphlinus
Firstly I'd like to say I have much admiration for your interest and erudition in 2D rendering!
A few years ago, I believe you shared on a (pcwalton's) pathfinder issue, a Google repository from the Fuschia monorepo.
This subrepository was about an internal sub fuschia project that seemed promising as it was about a "next generation" font renderer, a bit like a pathfinder competitor. Maybe it was vulkan based? I don't remember.
Anyway i can't find this repository/issue back (github search engine is bad) so I was wondering if you could find it back for me. And also if you had any update on the development of this renderer (since pathfinder unfortunately has stalled).
No problem if you don't have the time.
Thanks anyway for your contributions to computer engineering and your various amazing blogs posts!

**Comment by LifeIsStrange** [comment]
Okay I found it back on your Vision.MD, it's Spinel.
Although my question still stands, fo you have any news/opinion to share regarding spinel advancement and performance comparison vs piet gpu?

**Comment by raphlinus** [comment]
No worries. I don't have a lot I can say about Spinel progress, other than the fact that it does continue to be developed, and is a renderer for the Carnelian UI framework. Perhaps you can ask the author @allanmac whether there's more he'd like to say about it publicly at this time. I definitely want to acknowledge it as a major inspiration for my GPU rendering work.

Thanks for your kind words!

**Comment by LifeIsStrange** [comment]
Thanks for answering!
