### ISSUE TITLE
Writeup of Rust UI architecture ideas

### ISSUE THREAD

**Issue by raphlinus** [raphlinus/raphlinus.github.io#70]
I have another round of ideas for UI architecture in Rust. It's in the https://github.com/linebender/druid/tree/idiopath/idiopath branch, superseding [lasagna](https://github.com/linebender/druid/blob/lasagna/lasagna/src/rusty.rs). (Note: links to github branches aren't great, probably a PR, even a draft PR is better.)

This is a companion post in a way to #68 but the scope is different. While that one is about the challenge of actually shipping a UI, this one is effectively an academic exploration into the best way to express reactive UI. It's also a followup to previous SF meetup talks and architecture blog posts.

Here's something of an outline:

* Introduction of the problem
  - not sure how much to talk about existing Druid ("muggle") architecture, as most readers probably won't be familiar
  - ideas are based on a study of many UI systems, both in Rust and outside. Elm architecture as a foundation, SwiftUI is probably the closest precedent.
  - constraints: high performance, idiomatic Rust, good ergonomics
* High level overview of the architecture
  - three trees: view, state, widgets
  - app produces view tree, with "fairly short" lifetime
  - reconciliation (diffing) causes update to widget tree (also state tree, which is in support of reconciliation)
  - all 3 trees are strongly typed
  - every node has an id
    + actually messy question: id of node in the view tree, or every node in the widget tree? Most of the time they correspond
  - the widget tree handles mechanics of UI: drawing, processing input, etc
  - it produces (higher level) events, which are sent back to the app
  - key innovation: every event contains the id path (sequence of ids on the path from the root to the node that generated the event)
  - events are dispatched based on this id path
  - view tree contains callbacks, which have mutable access to app state
    + contrast elm, with manual dispatch from root of app
    + contrast nearly every other reactive UI framework, with shared mutable state of some kind
* Deeper dive: components
  - vanilla code for passing state (similar to React props) to child components
  - use of Adapt node to "lens" mutable state access
* Deeper dive: incrementality
  - Memoize node, avoids actually constructing view subtree
  - pointer equality on Rc values
    + in combination with Adapt, is actually sophisticated change tracking
  - ideas should generalize to collections, esp with immutable data types
* Deeper dive: type erasure
  - pattern works even with associated types and Self param (non object safe)
  - TODO: best references for this pattern? Is it known?
* Deeper dive: layering
  - widget tree works by itself, just not ergonomic
  - like Flutter but *unlike* SwiftUI and Elm, where lower layer is off limits
* Topics to touch on
  - accessibility
  - async
  - scripting
* Not in scope: styling
* Acknowledge inspirations and people: many Rust toolkits, Olivier, Manmeet, Taylor, Jan

**Comment by derekdreery** [comment]
Is 'use from within weakly typed/interpreted languages' another constraint?

**Comment by raphlinus** [comment]
I would consider it very much a "nice to have" but not a strong constraint. That said, I've actually prototyped Python bindings and that looks very encouraging.

**Comment by mwcampbell** [comment]
> accessibility

A few random thoughts on this:

It's good that you already have stable node IDs; these are required for a reliable accessibility implementation. (One of the earliest accessibility APIs, Microsoft Active Accessibility, didn't expose node IDs, and that caused me a lot of trouble as a Windows screen reader dev.)

I think it's a bit tricky to decide which layer in a UI architecture should generate the accessibility tree. On the one hand, you want to make sure you have high-level semantic information, e.g. a node with a role of "button" that either contains the name of the button or uses the "labelled by" relation to point to the node that has the name, as opposed to merely having low-level nodes like a border, a "clickable" node, and a text node. On the other hand, an accessibility tree also needs layout information; each visible node has to have a bounding rectangle, and for text nodes, you need more fine-grained information, like the list of actual on-screen lines of text, and even the position of each character. When I was at Microsoft, before the EdgeHTML engine was replaced by Chromium, I remember being surprised to find out that the EdgeHTML layout team owned accessibility for that engine. But now I see the sense in it.

**Comment by raphlinus** [comment]
A serious question: what do you think about the SwiftUI approach to specifying accessibility to an app? In exploring these ideas I'm finding that the decisions made by SwiftUI seem to map especially well suited to this architecture. Just for an example, SwiftUI's "stack" components don't take flex parameters the way Flutter's do, but rather rely on layoutPriority, so widgets default to a "reasonable" flex-ness (ScrollView and Button in the same stack, ScrollView will have higher priority and thus be flex).

I say this basically to propose the hypothesis that a (mostly) statically typed view tree is best served by a SwiftUI-like API, and that we should first try to understand that before proposing to do anything differently. I don't know if that's still true in accessibility land, which is why I'm asking you.

**Comment by mwcampbell** [comment]
Unfortunately, I haven't yet studied SwiftUI. I'll have to rectify that and get back to you.
