### ISSUE TITLE
Quadratic approximation of cubic beziers

### ISSUE THREAD

**Issue by mxsdev** [raphlinus/raphlinus.github.io#96]
Hi @raphlinus! First of all I want to say thank you for your blog, it has been an invaluable resource for me working on some of my projects.

In your [post on flatting quadratic bezier](https://raphlinus.github.io/graphics/curves/2019/12/23/flatten-quadbez.html), you say the following:

> In this blog post, we present an analytical approach to flattening quadratic Bézier curves into polylines. It is so good that it’s probably best to flatten other curve types (including cubic Béziers) by converting them to quadratics first, then applying the technique of this blog post.

Indeed, there are many approaches for flattening, filling, and stroking quadratic bezier that aren't readily extendable to cubic bezier. In some circumstances, it would seem ideal to approximate the cubic as quadratic (which could be done with way less segments than as polylines) and then proceed with the quadratic curves.

Do you have any advice and/or resources for carrying out this process of flattening cubic bezier to quadratic? I was able to find [this paper](https://yadda.icm.edu.pl/baztech/element/bwmeta1.element.baztech-d802f6a4-467a-4eb4-a21a-9321a6bb15340), but I didn't know if there were better approaches, or if you had covered this in one of your blog posts already that I missed, or if it is just obvious. If not, maybe this could make an interesting blog post? :)

Thanks!

**Comment by raphlinus** [comment]
Take a look at [to_quads](https://docs.rs/kurbo/latest/kurbo/struct.CubicBez.html#method.to_quads). This is not a sophisticated method; in particular it doesn't guarantee G1 continuity. If the latter is needed, there are things you can do. First, you have to subdivide at inflection points. Then, it boils down to computing an error metric, for which techniques developed for cubic simplification (ray casting) will probably work.

**Comment by mxsdev** [comment]
My bad on the link! [Here is the proper one](https://mat.polsl.pl/sjpam/zeszyty/z4/znps_mat_stos_04_2014_str_057-072.pdf). It would appear that the paper does not guarantee G1 continuity either, only that the frechet distance is proportional to the inverse cube of the number of (equal-sized wrt parameter) subdivisions.

Upon inspection, it would seem this is more or less equivalent to the kurbo implementation. The source code unfortunately links [to a 404](http://caffeineowl.com/graphics/2d/vectorial/cubic2quad01.html), but I'm assuming the idea behind both was some sort of optimization on the max distance between the cubic and an arbitrary middle point for a quadratic. Ostensibly this is possible analytically, hence the elegant result. 

For my purposes (mostly graphics rendering non-extreme cubics) I don't think G1 continuity is needed. Thanks for the details though, I'll probably look into techniques on cubic simplification just out of pure interest!
